---
abstract: 'Tools for the prolific module author'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Joseki
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::Cmd: 0
  Class::Accessor::Complex: 0
  Data::Rmap: 0
  Error: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 0
  File::Slurp: 0
  Getopt::Attribute: 0
  YAML: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Joseki
  homepage: http://search.cpan.org/dist/Dist-Joseki/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/dist-joseki.git
version: 0.20
