--- 
abstract: ~
author: 
  - "{% ELSE %}"
build_requires: 
  Test::Compile: 0
  Test::More: 0
  UNIVERSAL::require: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Dist-Joseki
no_index: 
  directory: 
    - inc
    - t
requires: 
  App::Cmd: 0
  Class::Accessor::Complex: 0
  Data::Rmap: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 0
  File::Slurp: 0
  Getopt::Attribute: 0
  IO::Prompt: 0
  Module::Changes: 0
  Module::CoreList: 0
  Module::ExtractUse: 0
  Parse::CPAN::Packages: 0
  Perl::Version: 0
  Template: 0
  Test::TAP::HTMLMatrix: 0
  Text::Diff: 0
  URI: 0
  Web::Scraper: 0
  YAML: 0
  perl: 5.6.0
version: 0.13
